---
apache_vhosts:
  - servername: dransible
    documentroot: "{{ project_docroot }}"

php_packages:
  - libapache2-mod-php{{ php_default_version_debian }}
  - libpcre3-dev
  - php-apcu
  - php-sqlite3
  - php{{ php_default_version_debian }}-cli
  - php{{ php_default_version_debian }}-common
  - php{{ php_default_version_debian }}-curl
  - php{{ php_default_version_debian }}-dev
  - php{{ php_default_version_debian }}-fpm
  - php{{ php_default_version_debian }}-gd
  - php{{ php_default_version_debian }}-imap
  - php{{ php_default_version_debian }}-json
  - php{{ php_default_version_debian }}-mbstring
  - php{{ php_default_version_debian }}-opcache
  - php{{ php_default_version_debian }}-xml

ansistrano_current_dir: current

project_deploy_dir: /var/www/app
project_subdir: web
project_docroot: "{{ project_deploy_dir }}/{{ ansistrano_current_dir }}/{{ project_subdir }}"

database_name: "{{ vault_database_name }}"
database_password: "{{ vault_database_password }}"
database_user: "{{ vault_database_user }}"
hash_salt: "{{ vault_hash_salt }}"

drupal_settings:
  - drupal_root: /tmp/app
    sites:
      - name: default
        settings:
          databases:
            default:
              default:
                driver: mysql
                host: localhost
                database: '{{ database_name }}'
                username: '{{ database_user }}'
                password: '{{ database_password }}'
          hash_salt: '{{ hash_salt }}'
          config_directories:
            sync: ../config/sync
