---
apache_vhosts:
  - servername: dransible
    documentroot: "{{ app_project_docroot }}"

php_packages:
  - libapache2-mod-php{{ php_default_version_debian }}
  - libpcre3-dev
  - php-apcu
  - php-sqlite3
  - php{{ php_default_version_debian }}-cli
  - php{{ php_default_version_debian }}-common
  - php{{ php_default_version_debian }}-curl
  - php{{ php_default_version_debian }}-dev
  - php{{ php_default_version_debian }}-fpm
  - php{{ php_default_version_debian }}-gd
  - php{{ php_default_version_debian }}-imap
  - php{{ php_default_version_debian }}-json
  - php{{ php_default_version_debian }}-mbstring
  - php{{ php_default_version_debian }}-opcache
  - php{{ php_default_version_debian }}-xml

ansistrano_current_dir: current

app_project_root: /var/www/app
app_project_subdir: web
app_project_docroot: "{{ app_project_root }}/{{ ansistrano_current_dir }}/{{ app_project_subdir }}"

app_db_name: "{{ vault_app_db_name }}"
app_db_password: "{{ vault_app_db_password }}"
app_db_user: "{{ vault_app_db_user }}"
app_hash_salt: "{{ vault_app_hash_salt }}"

drupal_settings:
  - drupal_root: '{{ app_project_docroot }}'
    sites:
      - name: default
        settings:
          databases:
            default:
              default:
                driver: mysql
                host: localhost
                database: '{{ app_db_name }}'
                username: '{{ app_db_user }}'
                password: '{{ app_db_password }}'
          hash_salt: '{{ app_hash_salt }}'
          config_directories:
            sync: ../config/sync
