---
apache_vhosts:
  - servername: dransible
    documentroot: "/var/www/app/web"

php_packages:
  - libapache2-mod-php{{ php_default_version_debian }}
  - libpcre3-dev
  - php-apcu
  - php-sqlite3
  - php{{ php_default_version_debian }}-cli
  - php{{ php_default_version_debian }}-common
  - php{{ php_default_version_debian }}-curl
  - php{{ php_default_version_debian }}-dev
  - php{{ php_default_version_debian }}-fpm
  - php{{ php_default_version_debian }}-gd
  - php{{ php_default_version_debian }}-imap
  - php{{ php_default_version_debian }}-json
  - php{{ php_default_version_debian }}-mbstring
  - php{{ php_default_version_debian }}-opcache
  - php{{ php_default_version_debian }}-xml
