---
- hosts: dransible
  become: true

  roles:
    - ansistrano.deploy

  vars_files:
    - vars/vars.yml

  vars:
    ansistrano_deploy_via: "rsync"
    ansistrano_deploy_from: "{{ playbook_dir }}/../"
    ansistrano_deploy_to: "{{ app_project_root }}"
    ansistrano_current_dir: current
    ansistrano_keep_releases: 5

  # tasks:
    # - name: Installing Composer dependencies
    #   composer:
    #     command: install
    #     working_dir: "{{ app_project_root }}"
