---
- hosts: dransible
  become: true

  roles:
    - ansistrano.deploy

  vars_files:
    - vars/vars.yml

  vars:
    ansistrano_deploy_via: "rsync"
    ansistrano_deploy_from: "{{ playbook_dir }}/../"
    ansistrano_deploy_to: "{{ app_project_root }}"
    ansistrano_current_dir: current
    ansistrano_keep_releases: 5
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/deploy/before-symlink.yml"
