---
- hosts: dransible
  become: true

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Creating project directory
      file:
        path: "{{ app_project_root }}"
        state: directory

    - name: Uploading application
      synchronize:
        src: ../../
        dest: "{{ app_project_root }}"

    - name: Installing Composer dependencies
      composer:
        command: install
        working_dir: "{{ app_project_root }}"
