---
- hosts: dransible
  become: true

  roles:
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer

  vars_files:
    - vars/main.yml
    - ../vars/main.yml

  tasks:
    - name: Create a database
      mysql_db:
        name: '{{ app_db_name }}'
        state: present

    - name: Add the database user
      mysql_user:
        name: '{{ app_db_user }}'
        password: '{{ app_db_password }}'
        priv: '*.*:ALL'
        state: present
