---
- hosts: dransible
  become: true

  roles:
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer

  vars_files:
    - vars/main.yml

  tasks:
    - name: Create a database
      mysql_db:
        name: drupal
        state: present

    - name: Add the database user
      mysql_user:
        name: drupal
        password: drupal
        priv: '*.*:ALL'
        state: present
